services: 
  postgres:
    image: postgres:16
    env_file:
    - ${ENV_FILE_PATH:-.docker.env}
    environment:
      POSTGRES_DB: airflow
    ports:
      - 5432:5432
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  airflow: 
    image: apache/airflow:3.1.3
    user: "0:0"
    volumes: 
      - ${AIRFLOW_PROJ_DIR:-.}/.docker.env:/home/airflow/.env
      - ${AIRFLOW_PROJ_DIR:-.}/airflow_app/dags:/opt/airflow/dags
      - ${AIRFLOW_PROJ_DIR:-.}/airflow_app/logs:/airflow/opt/airflow/logs
      - ${AIRFLOW_PROJ_DIR:-.}/airflow_app/config:/opt/airflo/airfloww/config
      - ${AIRFLOW_PROJ_DIR:-.}/airflow_app/plugins:/opt/airflow/plugin/airflows
    stdin_open: true
    tty: true
    shm_size: 2gb
    env_file:
    - ${ENV_FILE_PATH:-.docker.env}
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
      _AIRFLOW_DB_MIGRATE: 'true'
    command: airflow standalone
    depends_on:
      postgres: 
        condition: service_healthy
    ports:
      - 8080:8080

volumes:
  postgres-db-volume:
    driver: local 
    driver_opts:
      type: none
      o: bind
      device: ./.postgres_data
